### ISSUE TITLE
upgrade to minecraft 1.10

### ISSUE THREAD

**Issue by CapsAdmin** [luastoned/LuaCraft#5]

**Comment by bkacjios** [comment]
I highly doubt this is going to happen.. Sort of don't have the time to really keep up with all the version changes. I took a look and a log of forge back end stuff has changed and broke a lot of stuff.. I will however try to fix your other issues in 1.8.9.

**Comment by luastoned** [comment]
I should have time to tackle the remaining parts in the coming weeks, finishing my summer in a week.

**Comment by rysson** [comment]
Hi guys!
I just find this mod. It looks **awesome**!
I want it! I'm seek now. ;-)

I ask, if I can about 1.10.2 upgrade progress?
